import { StateValue } from 'xstate';
import { BotTurnActionState, CardInstance, EventInstance, IField, IPlayedCrop, MatchState, ToolInstance } from '..';
import * as cards from '../../cards';
export declare function assertIsNonNullable<T>(obj: T, message?: string): asserts obj is NonNullable<T>;
export declare function assertIsCardId(id: string): asserts id is keyof typeof cards;
export declare function assertIsToolCardId(id: string): asserts id is keyof typeof cards.toolCards;
export declare function assertIsEventCardInstance(card: CardInstance): asserts card is EventInstance;
export declare function assertIsToolCardInstance(card: CardInstance): asserts card is ToolInstance;
export declare function assertStringIsMatchState(str: string): asserts str is MatchState;
export declare function assertStateValueIsBotTurnActionState(stateValue: StateValue): asserts stateValue is BotTurnActionState;
export declare function assertIsPlayedCrop(plotContents: IField['cards'][0]): asserts plotContents is IPlayedCrop;
