import { default as React } from 'react';
import { CardViewProps } from './types';
export declare const cardClassName = "Card";
export declare const cardFlipWrapperClassName = "CardFlipWrapper";
export declare const cropWaterIndicatorOutlineColor = "#0072ff";
export declare const mobileActionButtonHeight = "2.5rem";
export declare const mobileActionButtonStackTopGap = "1rem";
export declare const getStackedActionButtonStackHeight: (actionButtonCount: number, gap: string) => string;
export declare const getStackedActionButtonsMarginTop: (actionButtonCount: number, gap: string) => string;
export declare const CardCore: React.ForwardRefExoticComponent<Omit<CardViewProps, "ref"> & React.RefAttributes<HTMLDivElement>>;
