import { StateValue, StateValueMap } from 'xstate';
import { CardInstance, ICard, ICrop, ICropPriceFluctuation, IField, IMatch, IPlayedCrop, IPlayer, ITable, ToolInstance, CropInstance, IPlayedTool, IPlayedCard } from '../';
import * as cards from '../../cards';
export declare const isNonNullObject: (value: unknown) => value is Record<string, unknown>;
export declare const isCardInstance: (obj: unknown) => obj is CardInstance;
export declare const isCrop: (obj: unknown) => obj is ICrop;
export declare const isCropCardInstance: (cardInstance: CardInstance) => cardInstance is CropInstance;
export declare const isPlantableCardInstance: (cardInstance: CardInstance) => cardInstance is CropInstance | ToolInstance;
export declare const isPlayedCrop: (obj: unknown) => obj is IPlayedCrop;
export declare const isPlayedTool: (obj: unknown) => obj is IPlayedTool;
export declare const isPlayedCard: (obj: unknown) => obj is IPlayedCard;
export declare const isField: (obj: unknown) => obj is IField;
export declare const isPlayer: (obj: unknown) => obj is IPlayer;
export declare const isTable: (obj: unknown) => obj is ITable;
export declare const isCropPriceFluctuation: (obj: unknown) => obj is ICropPriceFluctuation;
export declare const isMatch: (obj: unknown) => obj is IMatch;
export declare const isCardId: (id: string) => id is keyof typeof cards;
export declare const isCard: (obj: unknown) => obj is ICard;
export declare const isStateValueStateValueMap: (stateValue: StateValue) => stateValue is StateValueMap;
