import { ICard, Instance } from '../types';
export * as cropCards from './crops';
export * as eventCards from './events';
export * as toolCards from './tools';
export * as waterCards from './water';
export * from './crops';
export * from './events';
export * from './tools';
export * from './water';
export declare const instantiate: <T = ICard>(card: T) => T & Instance;
export declare const allCards: Record<string, ICard>;
