import { CropInstance, EventInstance, ToolInstance, WaterInstance } from '../../game/types';
export declare const stubCarrot: CropInstance;
export declare const stubCorn: CropInstance;
export declare const stubGarlic: CropInstance;
export declare const stubPea: CropInstance;
export declare const stubPotato: CropInstance;
export declare const stubPumpkin: CropInstance;
export declare const stubTomato: CropInstance;
export declare const stubWater: WaterInstance;
export declare const stubRain: EventInstance;
export declare const stubShovel: ToolInstance;
export declare const stubSprinkler: ToolInstance;
